// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANEaU6WFV5xSslFXZqlvLBeoR-GGS0tgI',
    appId: '1:708767251004:web:84a6065edc44117c15e139',
    messagingSenderId: '708767251004',
    projectId: 'flower-app-57f49',
    authDomain: 'flower-app-57f49.firebaseapp.com',
    storageBucket: 'flower-app-57f49.appspot.com',
    measurementId: 'G-6HFS1HZKDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKSsEFbjlquCZPu4tbxKIHYn7rzhpn8O8',
    appId: '1:708767251004:android:f62a2a18799475a415e139',
    messagingSenderId: '708767251004',
    projectId: 'flower-app-57f49',
    storageBucket: 'flower-app-57f49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3hRUzG8Cb4ngvjwSl80hFB3P6aJJDVKI',
    appId: '1:708767251004:ios:c46e5b4df29dbc9415e139',
    messagingSenderId: '708767251004',
    projectId: 'flower-app-57f49',
    storageBucket: 'flower-app-57f49.appspot.com',
    iosBundleId: 'com.example.flowerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3hRUzG8Cb4ngvjwSl80hFB3P6aJJDVKI',
    appId: '1:708767251004:ios:c46e5b4df29dbc9415e139',
    messagingSenderId: '708767251004',
    projectId: 'flower-app-57f49',
    storageBucket: 'flower-app-57f49.appspot.com',
    iosBundleId: 'com.example.flowerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANEaU6WFV5xSslFXZqlvLBeoR-GGS0tgI',
    appId: '1:708767251004:web:97aba29b60712e3315e139',
    messagingSenderId: '708767251004',
    projectId: 'flower-app-57f49',
    authDomain: 'flower-app-57f49.firebaseapp.com',
    storageBucket: 'flower-app-57f49.appspot.com',
    measurementId: 'G-V6Y34K02C8',
  );
}
